---
- name: Configure and Deploy Spring Boot App
  hosts: webserver # Replace with the target host from your inventory file
  become: yes  # This allows the tasks to run with sudo privileges

  tasks:
    - name: Install Python and pip
      become: yes
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3 python3-pip)

    - name: Install Docker python
      pip:
        name: docker
        state: present
      become: yes

    - name: Create Unix User and Group (demo)
      group:
        name: demo
        state: present

    - name: Create Unix User (demo)
      user:
        name: demo
        group: demo
        shell: /bin/bash
        home: /home/demo
        createhome: yes
      become_user: root  # Run this task as root

    - name: Deploy Spring Boot App Container
      docker_container:
        name: health-app
        #become_user: ansible
        #become_method: sudo
        image: docker.io/mohammedsait/medical  # Replace with your Docker image and tag
        state: started
        #restart_policy: always
        ports:
          - "8081:8080"
        privileged: true # Run this task as the 'demo' user
